// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package util

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NO_TYPE-0]
	_ = x[LEFT_PAREN-1]
	_ = x[RIGHT_PAREN-2]
	_ = x[LEFT_BRACE-3]
	_ = x[RIGHT_BRACE-4]
	_ = x[COMMA-5]
	_ = x[DOT-6]
	_ = x[MINUS-7]
	_ = x[PLUS-8]
	_ = x[SEMICOLON-9]
	_ = x[SLASH-10]
	_ = x[STAR-11]
	_ = x[BANG-12]
	_ = x[BANG_EQUAL-13]
	_ = x[EQUAL-14]
	_ = x[EQUAL_EQUAL-15]
	_ = x[GREAT-16]
	_ = x[GREAT_EQUAL-17]
	_ = x[LESS-18]
	_ = x[LESS_EQUAL-19]
	_ = x[IDENTIFIER-20]
	_ = x[STRING-21]
	_ = x[NUMBER-22]
	_ = x[AND-23]
	_ = x[CLASS-24]
	_ = x[ELSE-25]
	_ = x[FALSE-26]
	_ = x[FUN-27]
	_ = x[FOR-28]
	_ = x[IF-29]
	_ = x[NIL-30]
	_ = x[OR-31]
	_ = x[PRINT-32]
	_ = x[RETURN-33]
	_ = x[SUPER-34]
	_ = x[THIS-35]
	_ = x[TRUE-36]
	_ = x[VAR-37]
	_ = x[WHILE-38]
	_ = x[EOF-39]
}

const _TokenType_name = "NO_TYPELEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACECOMMADOTMINUSPLUSSEMICOLONSLASHSTARBANGBANG_EQUALEQUALEQUAL_EQUALGREATGREAT_EQUALLESSLESS_EQUALIDENTIFIERSTRINGNUMBERANDCLASSELSEFALSEFUNFORIFNILORPRINTRETURNSUPERTHISTRUEVARWHILEEOF"

var _TokenType_index = [...]uint8{0, 7, 17, 28, 38, 49, 54, 57, 62, 66, 75, 80, 84, 88, 98, 103, 114, 119, 130, 134, 144, 154, 160, 166, 169, 174, 178, 183, 186, 189, 191, 194, 196, 201, 207, 212, 216, 220, 223, 228, 231}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
